import type { Metadata } from "next";
import { Inter, Geist, Geist_Mono, Comforter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] }); // 加载本地字体
const comforter = Comforter({ subsets: ["latin"], weight: '400' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="trancy-zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
      >
        <div className={` ${inter.className}`}>
          {children}

        </div>
        <div className={` ${comforter.className}`}>
          {children}
        </div>
       
      </body>
    </html>
  );
}
